source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'

inhibit_all_warnings!

use_frameworks!

target 'SwiftyChatKitDemo' do
  
  pod 'OneSignal', '>= 2.11.2', '< 3.0'
  
  pod 'SwiftyChatKit', :path => '../SwiftyChatKit.podspec'
  pod 'SwiftyMessageKit', :path => '../../SwiftyMessageKit/SwiftyMessageKit.podspec'
end

target 'UOneSignal' do
  
  pod 'OneSignal', '>= 2.11.2', '< 3.0'
end

post_install do |installer|
  
  verTargets = ['SKPhotoBrowser', 'Result']
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0'
    end
    if verTargets.include? target.name
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = '5.0'
      end
    end
  end
end
