// swiftlint:disable all
// Generated using SwiftGen — https://github.com/SwiftGen/SwiftGen

#if os(macOS)
  import AppKit
#elseif os(iOS)
  import UIKit
#elseif os(tvOS) || os(watchOS)
  import UIKit
#endif

// Deprecated typealiases
@available(*, deprecated, renamed: "ImageAsset.Image", message: "This typealias will be removed in SwiftGen 7.0")
internal typealias AssetImageTypeAlias = ImageAsset.Image

// swiftlint:disable superfluous_disable_command file_length implicit_return

// MARK: - Asset Catalogs

// swiftlint:disable identifier_name line_length nesting type_body_length type_name
internal enum Asset {
  internal static let anchorAvatar = ImageAsset(name: "anchorAvatar")
  internal static let anchorBusy = ImageAsset(name: "anchorBusy")
  internal static let anchorCall = ImageAsset(name: "anchorCall")
  internal static let anchorChat = ImageAsset(name: "anchorChat")
  internal static let anchorChatG = ImageAsset(name: "anchorChatG")
  internal static let anchorComplete = ImageAsset(name: "anchorComplete")
  internal static let anchorFollowG = ImageAsset(name: "anchorFollowG")
  internal static let anchorFollowing = ImageAsset(name: "anchorFollowing")
  internal static let anchorLike = ImageAsset(name: "anchorLike")
  internal static let anchorScore = ImageAsset(name: "anchorScore")
  internal static let anchorTips = ImageAsset(name: "anchorTips")
  internal static let anchorVideo = ImageAsset(name: "anchorVideo")
  internal static let usermatchanchor912 = ImageAsset(name: "usermatchanchor912")
  internal static let usermatchanchor913 = ImageAsset(name: "usermatchanchor913")
  internal static let usermatchanchor914 = ImageAsset(name: "usermatchanchor914")
  internal static let usermatchanchor915 = ImageAsset(name: "usermatchanchor915")
  internal static let usermatchanchor916 = ImageAsset(name: "usermatchanchor916")
  internal static let usermatchanchor917 = ImageAsset(name: "usermatchanchor917")
  internal static let usermatchanchor918 = ImageAsset(name: "usermatchanchor918")
  internal static let usermatchanchor919 = ImageAsset(name: "usermatchanchor919")
  internal static let usermatchanchor920 = ImageAsset(name: "usermatchanchor920")
  internal static let usermatchanchor921 = ImageAsset(name: "usermatchanchor921")
  internal static let usermatchanchor922 = ImageAsset(name: "usermatchanchor922")
  internal static let usermatchanchor923 = ImageAsset(name: "usermatchanchor923")
  internal static let usermatchanchor924 = ImageAsset(name: "usermatchanchor924")
  internal static let usermatchanchor925 = ImageAsset(name: "usermatchanchor925")
  internal static let usermatchanchor926 = ImageAsset(name: "usermatchanchor926")
  internal static let usermatchanchor927 = ImageAsset(name: "usermatchanchor927")
  internal static let usermatchanchor928 = ImageAsset(name: "usermatchanchor928")
  internal static let usermatchanchor929 = ImageAsset(name: "usermatchanchor929")
  internal static let usermatchanchor930 = ImageAsset(name: "usermatchanchor930")
  internal static let usermatchanchor931 = ImageAsset(name: "usermatchanchor931")
  internal static let usermatchanchor932 = ImageAsset(name: "usermatchanchor932")
  internal static let usermatchanchor933 = ImageAsset(name: "usermatchanchor933")
  internal static let usermatchanchor934 = ImageAsset(name: "usermatchanchor934")
  internal static let usermatchanchor935 = ImageAsset(name: "usermatchanchor935")
  internal static let usermatchanchor936 = ImageAsset(name: "usermatchanchor936")
  internal static let usermatchanchor937 = ImageAsset(name: "usermatchanchor937")
  internal static let usermatchanchor938 = ImageAsset(name: "usermatchanchor938")
  internal static let usermatchanchor939 = ImageAsset(name: "usermatchanchor939")
  internal static let usermatchanchor940 = ImageAsset(name: "usermatchanchor940")
  internal static let usermatchanchor941 = ImageAsset(name: "usermatchanchor941")
  internal static let usermatchanchor942 = ImageAsset(name: "usermatchanchor942")
  internal static let usermatchanchor943 = ImageAsset(name: "usermatchanchor943")
  internal static let usermatchanchor944 = ImageAsset(name: "usermatchanchor944")
  internal static let usermatchanchor945 = ImageAsset(name: "usermatchanchor945")
  internal static let usermatchanchor946 = ImageAsset(name: "usermatchanchor946")
  internal static let usermatchanchor947 = ImageAsset(name: "usermatchanchor947")
  internal static let usermatchanchor948 = ImageAsset(name: "usermatchanchor948")
  internal static let usermatchanchor949 = ImageAsset(name: "usermatchanchor949")
  internal static let usermatchanchor950 = ImageAsset(name: "usermatchanchor950")
  internal static let usermatchanchor951 = ImageAsset(name: "usermatchanchor951")
  internal static let usermatchanchor952 = ImageAsset(name: "usermatchanchor952")
  internal static let usermatchanchor953 = ImageAsset(name: "usermatchanchor953")
  internal static let usermatchanchor954 = ImageAsset(name: "usermatchanchor954")
  internal static let usermatchanchor955 = ImageAsset(name: "usermatchanchor955")
  internal static let usermatchanchor956 = ImageAsset(name: "usermatchanchor956")
  internal static let arrowDown = ImageAsset(name: "arrowDown")
  internal static let arrowDownW = ImageAsset(name: "arrowDownW")
  internal static let arrowLeftW = ImageAsset(name: "arrowLeftW")
  internal static let arrowRight = ImageAsset(name: "arrowRight")
  internal static let arrowRightW = ImageAsset(name: "arrowRightW")
  internal static let arrowUp = ImageAsset(name: "arrowUp")
  internal static let btnBackRound = ImageAsset(name: "btnBackRound")
  internal static let btnBorder = ImageAsset(name: "btnBorder")
  internal static let btnBusy = ImageAsset(name: "btnBusy")
  internal static let btnCloseR = ImageAsset(name: "btnCloseR")
  internal static let btnCloseW = ImageAsset(name: "btnCloseW")
  internal static let btnOffline = ImageAsset(name: "btnOffline")
  internal static let btnOnline = ImageAsset(name: "btnOnline")
  internal static let btnPurple = ImageAsset(name: "btnPurple")
  internal static let btnRank = ImageAsset(name: "btnRank")
  internal static let btnReport = ImageAsset(name: "btnReport")
  internal static let chatAudioG = ImageAsset(name: "chatAudioG")
  internal static let chatAudioP = ImageAsset(name: "chatAudioP")
  internal static let chatFree = ImageAsset(name: "chatFree")
  internal static let chatIcon = ImageAsset(name: "chatIcon")
  internal static let chatMessage = ImageAsset(name: "chatMessage")
  internal static let chatPhoto = ImageAsset(name: "chatPhoto")
  internal static let chatService = ImageAsset(name: "chatService")
  internal static let chatTips = ImageAsset(name: "chatTips")
  internal static let comClose = ImageAsset(name: "comClose")
  internal static let comDownloadBG = ImageAsset(name: "comDownloadBG")
  internal static let comFirstTime = ImageAsset(name: "comFirstTime")
  internal static let comMoney = ImageAsset(name: "comMoney")
  internal static let comReload = ImageAsset(name: "comReload")
  internal static let comTag = ImageAsset(name: "comTag")
  internal static let comTime = ImageAsset(name: "comTime")
  internal static let comTreasureChest = ImageAsset(name: "comTreasureChest")
  internal static let ac = ImageAsset(name: "AC")
  internal static let ad = ImageAsset(name: "AD")
  internal static let ae = ImageAsset(name: "AE")
  internal static let af = ImageAsset(name: "AF")
  internal static let ag = ImageAsset(name: "AG")
  internal static let ai = ImageAsset(name: "AI")
  internal static let al = ImageAsset(name: "AL")
  internal static let am = ImageAsset(name: "AM")
  internal static let an = ImageAsset(name: "AN")
  internal static let ao = ImageAsset(name: "AO")
  internal static let aq = ImageAsset(name: "AQ")
  internal static let ar = ImageAsset(name: "AR")
  internal static let `as` = ImageAsset(name: "AS")
  internal static let at = ImageAsset(name: "AT")
  internal static let au = ImageAsset(name: "AU")
  internal static let aw = ImageAsset(name: "AW")
  internal static let ax = ImageAsset(name: "AX")
  internal static let az = ImageAsset(name: "AZ")
  internal static let ba = ImageAsset(name: "BA")
  internal static let bb = ImageAsset(name: "BB")
  internal static let bd = ImageAsset(name: "BD")
  internal static let be = ImageAsset(name: "BE")
  internal static let bf = ImageAsset(name: "BF")
  internal static let bg = ImageAsset(name: "BG")
  internal static let bh = ImageAsset(name: "BH")
  internal static let bi = ImageAsset(name: "BI")
  internal static let bj = ImageAsset(name: "BJ")
  internal static let bl = ImageAsset(name: "BL")
  internal static let bm = ImageAsset(name: "BM")
  internal static let bn = ImageAsset(name: "BN")
  internal static let bo = ImageAsset(name: "BO")
  internal static let bq = ImageAsset(name: "BQ")
  internal static let br = ImageAsset(name: "BR")
  internal static let bs = ImageAsset(name: "BS")
  internal static let bt = ImageAsset(name: "BT")
  internal static let bv = ImageAsset(name: "BV")
  internal static let bw = ImageAsset(name: "BW")
  internal static let by = ImageAsset(name: "BY")
  internal static let bz = ImageAsset(name: "BZ")
  internal static let ca = ImageAsset(name: "CA")
  internal static let cc = ImageAsset(name: "CC")
  internal static let cd = ImageAsset(name: "CD")
  internal static let cf = ImageAsset(name: "CF")
  internal static let cg = ImageAsset(name: "CG")
  internal static let ch = ImageAsset(name: "CH")
  internal static let ci = ImageAsset(name: "CI")
  internal static let ck = ImageAsset(name: "CK")
  internal static let cl = ImageAsset(name: "CL")
  internal static let cm = ImageAsset(name: "CM")
  internal static let cn = ImageAsset(name: "CN")
  internal static let co = ImageAsset(name: "CO")
  internal static let cr = ImageAsset(name: "CR")
  internal static let cu = ImageAsset(name: "CU")
  internal static let cv = ImageAsset(name: "CV")
  internal static let cw = ImageAsset(name: "CW")
  internal static let cx = ImageAsset(name: "CX")
  internal static let cy = ImageAsset(name: "CY")
  internal static let cz = ImageAsset(name: "CZ")
  internal static let de = ImageAsset(name: "DE")
  internal static let dj = ImageAsset(name: "DJ")
  internal static let dk = ImageAsset(name: "DK")
  internal static let dm = ImageAsset(name: "DM")
  internal static let `do` = ImageAsset(name: "DO")
  internal static let dz = ImageAsset(name: "DZ")
  internal static let ec = ImageAsset(name: "EC")
  internal static let ee = ImageAsset(name: "EE")
  internal static let eg = ImageAsset(name: "EG")
  internal static let eh = ImageAsset(name: "EH")
  internal static let er = ImageAsset(name: "ER")
  internal static let es = ImageAsset(name: "ES")
  internal static let et = ImageAsset(name: "ET")
  internal static let fi = ImageAsset(name: "FI")
  internal static let fj = ImageAsset(name: "FJ")
  internal static let fk = ImageAsset(name: "FK")
  internal static let fm = ImageAsset(name: "FM")
  internal static let fo = ImageAsset(name: "FO")
  internal static let fr = ImageAsset(name: "FR")
  internal static let fx = ImageAsset(name: "FX")
  internal static let ga = ImageAsset(name: "GA")
  internal static let gb = ImageAsset(name: "GB")
  internal static let gd = ImageAsset(name: "GD")
  internal static let ge = ImageAsset(name: "GE")
  internal static let gf = ImageAsset(name: "GF")
  internal static let gg = ImageAsset(name: "GG")
  internal static let gh = ImageAsset(name: "GH")
  internal static let gi = ImageAsset(name: "GI")
  internal static let gl = ImageAsset(name: "GL")
  internal static let gm = ImageAsset(name: "GM")
  internal static let gn = ImageAsset(name: "GN")
  internal static let gp = ImageAsset(name: "GP")
  internal static let gq = ImageAsset(name: "GQ")
  internal static let gr = ImageAsset(name: "GR")
  internal static let gs = ImageAsset(name: "GS")
  internal static let gt = ImageAsset(name: "GT")
  internal static let gu = ImageAsset(name: "GU")
  internal static let gw = ImageAsset(name: "GW")
  internal static let gy = ImageAsset(name: "GY")
  internal static let hk = ImageAsset(name: "HK")
  internal static let hm = ImageAsset(name: "HM")
  internal static let hn = ImageAsset(name: "HN")
  internal static let hr = ImageAsset(name: "HR")
  internal static let ht = ImageAsset(name: "HT")
  internal static let hu = ImageAsset(name: "HU")
  internal static let id = ImageAsset(name: "ID")
  internal static let ie = ImageAsset(name: "IE")
  internal static let il = ImageAsset(name: "IL")
  internal static let im = ImageAsset(name: "IM")
  internal static let `in` = ImageAsset(name: "IN")
  internal static let io = ImageAsset(name: "IO")
  internal static let iq = ImageAsset(name: "IQ")
  internal static let ir = ImageAsset(name: "IR")
  internal static let `is` = ImageAsset(name: "IS")
  internal static let it = ImageAsset(name: "IT")
  internal static let je = ImageAsset(name: "JE")
  internal static let jm = ImageAsset(name: "JM")
  internal static let jo = ImageAsset(name: "JO")
  internal static let jp = ImageAsset(name: "JP")
  internal static let ke = ImageAsset(name: "KE")
  internal static let kg = ImageAsset(name: "KG")
  internal static let kh = ImageAsset(name: "KH")
  internal static let ki = ImageAsset(name: "KI")
  internal static let km = ImageAsset(name: "KM")
  internal static let kn = ImageAsset(name: "KN")
  internal static let kp = ImageAsset(name: "KP")
  internal static let kr = ImageAsset(name: "KR")
  internal static let kt = ImageAsset(name: "KT")
  internal static let kw = ImageAsset(name: "KW")
  internal static let ky = ImageAsset(name: "KY")
  internal static let kz = ImageAsset(name: "KZ")
  internal static let la = ImageAsset(name: "LA")
  internal static let lb = ImageAsset(name: "LB")
  internal static let lc = ImageAsset(name: "LC")
  internal static let li = ImageAsset(name: "LI")
  internal static let lk = ImageAsset(name: "LK")
  internal static let lr = ImageAsset(name: "LR")
  internal static let ls = ImageAsset(name: "LS")
  internal static let lt = ImageAsset(name: "LT")
  internal static let lu = ImageAsset(name: "LU")
  internal static let lv = ImageAsset(name: "LV")
  internal static let ly = ImageAsset(name: "LY")
  internal static let ma = ImageAsset(name: "MA")
  internal static let mc = ImageAsset(name: "MC")
  internal static let md = ImageAsset(name: "MD")
  internal static let me = ImageAsset(name: "ME")
  internal static let mf = ImageAsset(name: "MF")
  internal static let mg = ImageAsset(name: "MG")
  internal static let mh = ImageAsset(name: "MH")
  internal static let mk = ImageAsset(name: "MK")
  internal static let ml = ImageAsset(name: "ML")
  internal static let mm = ImageAsset(name: "MM")
  internal static let mn = ImageAsset(name: "MN")
  internal static let mo = ImageAsset(name: "MO")
  internal static let mp = ImageAsset(name: "MP")
  internal static let mq = ImageAsset(name: "MQ")
  internal static let mr = ImageAsset(name: "MR")
  internal static let ms = ImageAsset(name: "MS")
  internal static let mt = ImageAsset(name: "MT")
  internal static let mu = ImageAsset(name: "MU")
  internal static let mv = ImageAsset(name: "MV")
  internal static let mw = ImageAsset(name: "MW")
  internal static let mx = ImageAsset(name: "MX")
  internal static let my = ImageAsset(name: "MY")
  internal static let mz = ImageAsset(name: "MZ")
  internal static let na = ImageAsset(name: "NA")
  internal static let nc = ImageAsset(name: "NC")
  internal static let ne = ImageAsset(name: "NE")
  internal static let nf = ImageAsset(name: "NF")
  internal static let ng = ImageAsset(name: "NG")
  internal static let ni = ImageAsset(name: "NI")
  internal static let nl = ImageAsset(name: "NL")
  internal static let no = ImageAsset(name: "NO")
  internal static let np = ImageAsset(name: "NP")
  internal static let nr = ImageAsset(name: "NR")
  internal static let nu = ImageAsset(name: "NU")
  internal static let nz = ImageAsset(name: "NZ")
  internal static let om = ImageAsset(name: "OM")
  internal static let pa = ImageAsset(name: "PA")
  internal static let pe = ImageAsset(name: "PE")
  internal static let pf = ImageAsset(name: "PF")
  internal static let pg = ImageAsset(name: "PG")
  internal static let ph = ImageAsset(name: "PH")
  internal static let pk = ImageAsset(name: "PK")
  internal static let pl = ImageAsset(name: "PL")
  internal static let pm = ImageAsset(name: "PM")
  internal static let pn = ImageAsset(name: "PN")
  internal static let pr = ImageAsset(name: "PR")
  internal static let ps = ImageAsset(name: "PS")
  internal static let pt = ImageAsset(name: "PT")
  internal static let pw = ImageAsset(name: "PW")
  internal static let py = ImageAsset(name: "PY")
  internal static let qa = ImageAsset(name: "QA")
  internal static let re = ImageAsset(name: "RE")
  internal static let ro = ImageAsset(name: "RO")
  internal static let rs = ImageAsset(name: "RS")
  internal static let ru = ImageAsset(name: "RU")
  internal static let rw = ImageAsset(name: "RW")
  internal static let sa = ImageAsset(name: "SA")
  internal static let sb = ImageAsset(name: "SB")
  internal static let sc = ImageAsset(name: "SC")
  internal static let sd = ImageAsset(name: "SD")
  internal static let se = ImageAsset(name: "SE")
  internal static let sg = ImageAsset(name: "SG")
  internal static let sh = ImageAsset(name: "SH")
  internal static let si = ImageAsset(name: "SI")
  internal static let sj = ImageAsset(name: "SJ")
  internal static let sk = ImageAsset(name: "SK")
  internal static let sl = ImageAsset(name: "SL")
  internal static let sm = ImageAsset(name: "SM")
  internal static let sn = ImageAsset(name: "SN")
  internal static let so = ImageAsset(name: "SO")
  internal static let sr = ImageAsset(name: "SR")
  internal static let ss = ImageAsset(name: "SS")
  internal static let st = ImageAsset(name: "ST")
  internal static let sv = ImageAsset(name: "SV")
  internal static let sx = ImageAsset(name: "SX")
  internal static let sy = ImageAsset(name: "SY")
  internal static let sz = ImageAsset(name: "SZ")
  internal static let tc = ImageAsset(name: "TC")
  internal static let td = ImageAsset(name: "TD")
  internal static let tf = ImageAsset(name: "TF")
  internal static let tg = ImageAsset(name: "TG")
  internal static let th = ImageAsset(name: "TH")
  internal static let tj = ImageAsset(name: "TJ")
  internal static let tk = ImageAsset(name: "TK")
  internal static let tl = ImageAsset(name: "TL")
  internal static let tm = ImageAsset(name: "TM")
  internal static let tn = ImageAsset(name: "TN")
  internal static let to = ImageAsset(name: "TO")
  internal static let tr = ImageAsset(name: "TR")
  internal static let tt = ImageAsset(name: "TT")
  internal static let tv = ImageAsset(name: "TV")
  internal static let tw = ImageAsset(name: "TW")
  internal static let tz = ImageAsset(name: "TZ")
  internal static let ua = ImageAsset(name: "UA")
  internal static let ug = ImageAsset(name: "UG")
  internal static let um = ImageAsset(name: "UM")
  internal static let us = ImageAsset(name: "US")
  internal static let uy = ImageAsset(name: "UY")
  internal static let uz = ImageAsset(name: "UZ")
  internal static let va = ImageAsset(name: "VA")
  internal static let vc = ImageAsset(name: "VC")
  internal static let ve = ImageAsset(name: "VE")
  internal static let vg = ImageAsset(name: "VG")
  internal static let vi = ImageAsset(name: "VI")
  internal static let vn = ImageAsset(name: "VN")
  internal static let vu = ImageAsset(name: "VU")
  internal static let wf = ImageAsset(name: "WF")
  internal static let ws = ImageAsset(name: "WS")
  internal static let xk = ImageAsset(name: "XK")
  internal static let ye = ImageAsset(name: "YE")
  internal static let yt = ImageAsset(name: "YT")
  internal static let yu = ImageAsset(name: "YU")
  internal static let za = ImageAsset(name: "ZA")
  internal static let zm = ImageAsset(name: "ZM")
  internal static let zr = ImageAsset(name: "ZR")
  internal static let zw = ImageAsset(name: "ZW")
  internal static let defaultAvatar = ImageAsset(name: "defaultAvatar")
  internal static let defaultBanner = ImageAsset(name: "defaultBanner")
  internal static let defaultImage = ImageAsset(name: "defaultImage")
  internal static let defaultNodata = ImageAsset(name: "defaultNodata")
  internal static let defaultTransparent = ImageAsset(name: "defaultTransparent")
  internal static let defaultTransparentBig = ImageAsset(name: "defaultTransparentBig")
  internal static let defaultTransparentDown = ImageAsset(name: "defaultTransparentDown")
  internal static let hudCircle = ImageAsset(name: "hudCircle")
  internal static let iconDiamond1 = ImageAsset(name: "iconDiamond1")
  internal static let iconDiamond2 = ImageAsset(name: "iconDiamond2")
  internal static let iconDiamond3 = ImageAsset(name: "iconDiamond3")
  internal static let loginBG = ImageAsset(name: "loginBG")
  internal static let loginFemale = ImageAsset(name: "loginFemale")
  internal static let loginGender = ImageAsset(name: "loginGender")
  internal static let loginMale = ImageAsset(name: "loginMale")
  internal static let loginUpdate = ImageAsset(name: "loginUpdate")
  internal static let matchBothW = ImageAsset(name: "matchBothW")
  internal static let matchFemaleG = ImageAsset(name: "matchFemaleG")
  internal static let matchFemaleR = ImageAsset(name: "matchFemaleR")
  internal static let matchFemaleW = ImageAsset(name: "matchFemaleW")
  internal static let matchLooking = ImageAsset(name: "matchLooking")
  internal static let matchMaleG = ImageAsset(name: "matchMaleG")
  internal static let matchMaleP = ImageAsset(name: "matchMaleP")
  internal static let matchMaleW = ImageAsset(name: "matchMaleW")
  internal static let rankGiftPack = ImageAsset(name: "rankGiftPack")
  internal static let rankGoldHead = ImageAsset(name: "rankGoldHead")
  internal static let rankHot = ImageAsset(name: "rankHot")
  internal static let rankLike = ImageAsset(name: "rankLike")
  internal static let rankLoverHead = ImageAsset(name: "rankLoverHead")
  internal static let rankMoney = ImageAsset(name: "rankMoney")
  internal static let rankTop1 = ImageAsset(name: "rankTop1")
  internal static let rankTop2 = ImageAsset(name: "rankTop2")
  internal static let rankTop3 = ImageAsset(name: "rankTop3")
  internal static let svgaFirstPack = DataAsset(name: "svgaFirstPack")
  internal static let tabMatch = ImageAsset(name: "tabMatch")
  internal static let tabMatchS = ImageAsset(name: "tabMatchS")
  internal static let tabMseeage = ImageAsset(name: "tabMseeage")
  internal static let tabMseeageS = ImageAsset(name: "tabMseeageS")
  internal static let tabSearch = ImageAsset(name: "tabSearch")
  internal static let tabSearchS = ImageAsset(name: "tabSearchS")
  internal static let tabSetting = ImageAsset(name: "tabSetting")
  internal static let tabSettingS = ImageAsset(name: "tabSettingS")
  internal static let userBlacklist = ImageAsset(name: "userBlacklist")
  internal static let userBlacklistB = ImageAsset(name: "userBlacklistB")
  internal static let userChat = ImageAsset(name: "userChat")
  internal static let userClose = ImageAsset(name: "userClose")
  internal static let userDelete = ImageAsset(name: "userDelete")
  internal static let userEdit = ImageAsset(name: "userEdit")
  internal static let userEditProfile = ImageAsset(name: "userEditProfile")
  internal static let userFellow = ImageAsset(name: "userFellow")
  internal static let userModify = ImageAsset(name: "userModify")
  internal static let userRecord = ImageAsset(name: "userRecord")
  internal static let userSettings = ImageAsset(name: "userSettings")
  internal static let userSupport = ImageAsset(name: "userSupport")
  internal static let userincognito = ImageAsset(name: "userincognito")
}
// swiftlint:enable identifier_name line_length nesting type_body_length type_name

// MARK: - Implementation Details

internal struct DataAsset {
  internal fileprivate(set) var name: String

  #if os(iOS) || os(tvOS) || os(macOS)
  @available(iOS 9.0, macOS 10.11, *)
  internal var data: NSDataAsset {
    guard let data = NSDataAsset(asset: self) else {
      fatalError("Unable to load data asset named \(name).")
    }
    return data
  }
  #endif
}

#if os(iOS) || os(tvOS) || os(macOS)
@available(iOS 9.0, macOS 10.11, *)
internal extension NSDataAsset {
  convenience init?(asset: DataAsset) {
    let bundle = BundleToken.bundle
    #if os(iOS) || os(tvOS)
    self.init(name: asset.name, bundle: bundle)
    #elseif os(macOS)
    self.init(name: NSDataAsset.Name(asset.name), bundle: bundle)
    #endif
  }
}
#endif

internal struct ImageAsset {
  internal fileprivate(set) var name: String

  #if os(macOS)
  internal typealias Image = NSImage
  #elseif os(iOS) || os(tvOS) || os(watchOS)
  internal typealias Image = UIImage
  #endif

  internal var image: Image {
    let bundle = BundleToken.bundle
    #if os(iOS) || os(tvOS)
    let image = Image(named: name, in: bundle, compatibleWith: nil)
    #elseif os(macOS)
    let name = NSImage.Name(self.name)
    let image = (bundle == .main) ? NSImage(named: name) : bundle.image(forResource: name)
    #elseif os(watchOS)
    let image = Image(named: name)
    #endif
    guard let result = image else {
      fatalError("Unable to load image asset named \(name).")
    }
    return result
  }
}

internal extension ImageAsset.Image {
  @available(macOS, deprecated,
    message: "This initializer is unsafe on macOS, please use the ImageAsset.image property")
  convenience init?(asset: ImageAsset) {
    #if os(iOS) || os(tvOS)
    let bundle = BundleToken.bundle
    self.init(named: asset.name, in: bundle, compatibleWith: nil)
    #elseif os(macOS)
    self.init(named: NSImage.Name(asset.name))
    #elseif os(watchOS)
    self.init(named: asset.name)
    #endif
  }
}

// swiftlint:disable convenience_type
private final class BundleToken {
  static let bundle: Bundle = {
    return Bundle.chatAssetBundle
  }()
}
// swiftlint:enable convenience_type
